migrate to new gradle plugin
akonior/icon-version pull request #14
Opened 2018-08-02 14:37 UTC by Mu3AHTPOn

Gradle plugin version was updated.
Paths to resources dir and manifest file were updated.
Searching for roundIcon and adaptive icons was added.
Version drawing moved to center in order to avoid text cutting for rounded icons on the latest Android.

2018-08-03 16:09 UTC, akonior requested changes
Thanks a lot for this PR! Would you be able to update to latest Android gradle plugin?

2018-08-03 16:09 UTC, akonior commented on build.gradle
> -    compile 'com.android.tools.build:gradle:1.2.3'
Why `2.3.3`? I think this is old version. The newest is `3.1.0`. Plz check https://developer.android.com/studio/releases/gradle-plugin

2018-08-06 10:34 UTC, Mu3AHTPOn commented
I've updated Android gradle plugin to the latest version (3.1.3). Please take a look

2018-08-12 06:59 UTC, akonior approved these changes

2018-08-12 06:59 UTC, merged